### ISSUE TITLE
Integrate skale-contracts

### ISSUE THREAD

**Issue by DimaStebaev** [skalenetwork/skale.py#540]
```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skale-contracts/issues/32
- [ ] https://github.com/skalenetwork/skale-contracts/issues/34
- [ ] https://github.com/skalenetwork/skale-contracts/issues/52
```
